[book]
authors = ["LuisAlvarado3"]
language = "en"
multilingual = false
src = "src"
title = "Modelo de posicionamiento espacial"

[output.html]
mathjax-support = true
additional-css  = ["./src/css/style.css"]